/*
 * This source file was generated by the Gradle 'init' task
 */
package de.bonbonkocher.launcher;

import de.bonbonkocher.launcher.window.MainWindow;

public class App {
    public static void main(String[] args) {
        //MainWindow gameWindow = new MainWindow();
        new MainWindow();
    }
    
}
